"""empty message

Revision ID: 52e2f515bc8c
Revises: 6b16f3bbcf7b
Create Date: 2023-11-10 01:07:54.248091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52e2f515bc8c'
down_revision = '6b16f3bbcf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
