"""empty message

Revision ID: b88fe6c8bc50
Revises: 52e2f515bc8c
Create Date: 2023-11-10 01:08:51.932004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b88fe6c8bc50'
down_revision = '52e2f515bc8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('created')

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_column('created')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
