"""empty message

Revision ID: f2c219c4e8dc
Revises: 2633615d33cd
Create Date: 2024-02-21 23:54:26.462749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2c219c4e8dc'
down_revision = '2633615d33cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships_details', schema=None) as batch_op:
        batch_op.alter_column('crew',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships_details', schema=None) as batch_op:
        batch_op.alter_column('crew',
               existing_type=sa.String(length=50),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
